<?php
return [
    [
        'name' => 'Sitewide Options',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_site_settings',
    ],
    [
        'name'    => 'Cruise Year',
        'desc'    => '',
        'id'      => 'mac_cruise_year',
        'type'    => 'text_small',
        'default' => false,
    ],
    [
        'name'    => 'Talent Year',
        'desc'    => 'Which year worth of talent should we load on the front page?',
        'id'      => 'mac_talent_year',
        'type'    => 'text_small',
        'default' => false,
    ],
    [
        'name'    => 'Enable booking',
        'desc'    => 'This determines wheter the two buttons show up under the header on the front page',
        'id'      => 'mac_enable_booking',
        'type'    => 'checkbox',
        'default' => false,
    ],
    [
        'name'    => 'Booking Path',
        'desc'    => 'Root relative URL for booking site',
        'id'      => 'mac_booking_url',
        'type'    => 'text_medium',
        'default' => false,
    ],
    [
        'name'    => 'Contact Form Email Address',
        'desc'    => '',
        'id'      => 'mac_contact_email',
        'type'    => 'text_email',
        'default' => false,
    ],
    [
        'name' => 'Hero Section Options',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_hero_settings',
    ],
    [
        'name'    => 'Travel Dates',
        'desc'    => '',
        'id'      => 'mac_travel_dates',
        'type'    => 'textarea_small',
        'default' => false,
    ],
    [
        'name'    => 'Button Call to Action',
        'desc'    => '',
        'id'      => 'mac_button_cta',
        'type'    => 'text_medium',
        'default' => false,
    ],
    [
        'name'    => 'Travel Description',
        'desc'    => '',
        'id'      => 'mac_travel_description',
        'type'    => 'textarea',
        'default' => false,
    ],
    [
        'name'    => 'Travel Description (More)',
        'desc'    => '',
        'id'      => 'mac_travel_description_more',
        'type'    => 'textarea',
        'default' => false,
    ],
    [
        'name'    => 'Hero Book Now Button',
        'desc'    => '',
        'id'      => 'mac_hero_book_now',
        'type'    => 'text_medium',
        'default' => false,
    ],
    [
        'name'    => 'Hero Already Booked Button',
        'desc'    => '',
        'id'      => 'mac_hero_already_booked',
        'type'    => 'text_medium',
        'default' => false,
    ],
    [
        'name'    => 'Hero Already Booked URL',
        'desc'    => '',
        'id'      => 'mac_hero_already_booked_url',
        'type'    => 'text_medium',
        'default' => false,
    ],
    [
        'name'    => 'Mailing List Call to Action',
        'desc'    => 'split lines with pipe (|)',
        'id'      => 'mac_mailing_list_cta',
        'type'    => 'textarea_small',
        'default' => 'Join the | JoCo Cruise Mailing List',
    ],
    [
        'name'    => 'Link to Facebook Page',
        'desc'    => '',
        'id'      => 'mac_facebook_url',
        'type'    => 'text_url',
        'default' => false,
    ],
    [
        'name'    => 'Link to Twitter',
        'desc'    => '',
        'id'      => 'mac_twitter_url',
        'type'    => 'text_url',
        'default' => false,
    ],
    [
        'name'    => 'Link to RSS feed',
        'desc'    => '',
        'id'      => 'mac_feed_url',
        'type'    => 'text_url',
        'default' => false,
    ],
    [
        'name'    => 'Link to Instagram',
        'desc'    => '',
        'id'      => 'mac_insta_url',
        'type'    => 'text_url',
        'default' => false,
    ],
    [
        'name' => 'Artist Settings',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_artist_settings',
    ],
    [
        'name'    => 'Talent Section Header',
        'desc'    => 'split lines with pipe (|)',
        'id'      => 'mac_talent_header',
        'type'    => 'textarea_small',
        'default' => 'Enjoy the Following | Performers and Featured Guests',
    ],
    [
        'name'    => 'Performer Intro Content (Markdown)',
        'desc'    => '',
        'id'      => 'mac_talent_intro_para',
        'type'    => 'textarea_small',
        'default' => '',
    ],
    [
        'name'    => 'Performer Header',
        'desc'    => 'Split lines with pipe (|) / Leave blank to omit',
        'id'      => 'mac_performer_header',
        'type'    => 'text_medium',
        'default' => '',
    ],
    [
        'name'    => 'Featured Guest Header',
        'desc'    => 'Split lines with pipe (|) / Leave blank to omit',
        'id'      => 'mac_featuredguest_header',
        'type'    => 'text_medium',
        'default' => '',
    ],
    [
        'name'    => 'Even More Header',
        'desc'    => 'Split lines with pipe (|) / Leave blank to omit',
        'id'      => 'mac_evenmore_header',
        'type'    => 'text_medium',
        'default' => '',
    ],
    [
        'name'    => 'Coming Soon Header',
        'desc'    => 'Split lines with pipe (|) / Leave blank to omit',
        'id'      => 'coming_soon_header',
        'type'    => 'text_medium',
        'default' => '',
    ],
    [
        'name' => 'Contact Settings',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_contact_settings',
    ],
    [
        'name' => 'General Questions Header',
        'id'   => 'mac_general_questions_header',
        'type' => 'text_medium',
    ],
    [
        'name' => 'General Questions Address',
        'id'   => 'mac_general_questions_address_header',
        'type' => 'text_medium',
    ],
    [
        'name' => 'Booking Questions Header',
        'id'   => 'mac_booking_questions_header',
        'type' => 'text_medium',
    ],
    [
        'name' => 'Booking Questions Address',
        'id'   => 'mac_booking_questions_address_header',
        'type' => 'text_medium',
    ],
    [
        'name' => 'Phone Questions Header',
        'id'   => 'mac_phone_questions_header',
        'type' => 'text_medium',
    ],
    [
        'name' => 'Phone Questions Number',
        'id'   => 'mac_phone_questions_address_header',
        'type' => 'text_medium',
    ],
    [
        'name' => 'Map Settings',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_map_settings',
    ],
    [
        'name' => 'Map Info Copy (narrow-width only)',
        'id'   => 'mac_map_copy',
        'type' => 'textarea_small',
    ],
    [
        'name' => 'News Settings',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_news_settings',
    ],
    [
        'name' => 'News Header',
        'id'   => 'mac_news_header',
        'type' => 'textarea_small',
    ],
    [
        'name' => 'News "View All" Copy',
        'id'   => 'mac_news_view_all',
        'type' => 'text_medium',
    ],
    [
        'name' => 'News "View All" URL',
        'id'   => 'mac_news_view_all_url',
        'type' => 'text_medium',
    ],
    [
        'name' => 'FAQ Settings',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_faq_settings',
    ],
    [
        'name'    => 'FAQ Categories',
        'desc'    => 'pipe delimited categories for faqs, in order!',
        'id'      => 'mac_piped_cats',
        'type'    => 'textarea_code',
        'default' => 'What the Heck?|Booking Questions|I’m Booked! Now What?|Managing my Booking',
    ],
    [
        'name' => 'Footer Settings',
        'desc' => '',
        'type' => 'title',
        'id'   => 'mac_footer_settings',
    ],
    [
        'name' => 'Footer Text',
        'id'   => 'mac_footer_text',
        'type' => 'textarea_small',
    ],
];
?>
